### ISSUE TITLE
Front wheel and using Pico as replacement for Arduino Nano

### ISSUE THREAD

**Issue by mattsoh** [ukmars/ukmarsbot#36]
Hi,

I would like to ask what would be recommended for the front wheel (ball caster etc.), as well as what size.

Also is using the Raspberry Pi Pico a suitable replacement for the Arduino Nano (in terms of hardware capability).

Thanks!

-Matthew

**Comment by micromouseonline** [comment]
I normally just glue on a thick piece of plastic with a bit of a ramp so that it can ride over bumps. You can 3D print a part or build it up from whtever you have to hand. Some people use a Nylon M3 screw and nut. Make sure that the mouse can rock to and fro a little so that dips in the running surface don't leave it stranded.

There is a whole group of people working on a Pi Pico version of UKMARSBOT. Progress is a little slow but we are getting there. A note went out to the UKMARS mailing list a couple of days ago.

If you are not a member of UKMARS, consider joining to help support the effort, learn more about progress and perhaps contribute some ideas of your own.
